WITH UNADJ_MARGIN AS 
(
	SELECT   
	left(ORG_CODE,4) AS COMPANY_CODE, 
	--FISCAL_YEAR_VARIANT,
	FISCAL_YEAR, 
	JOURNAL_PERIOD,
	CAST (YEAR(GETDATE()) AS VARCHAR) AS REPYEAR,
	CAST (MONTH(GETDATE()) -1 AS VARCHAR) AS REPMONTH,
	(CASE WHEN JOURNAL_PERIOD= '00' THEN '0' ELSE LTRIM(JOURNAL_PERIOD,'0') END) AS COMP_PERIOD,
	--DOCUMENT_NUMBER_GENERAL_LEDGER_VIEW, 
	--LINE_ITEM_GENERAL_LEDGER_VIEW,
	--POSTING_DATE_IN_THE_DOCUMENT,
	MAIN_ACCOUNT_ID,
	JOURNAL_ENTRY_COMMENT_1 AS INTCO_MP,
	--OFFSETTING_ACCOUNT,
	--SALES_DOCUMENT,
	'MP' as SOURCE,
	SUM (((CASE WHEN MAIN_ACCOUNT_ID = '3211' THEN JOURNAL_ENTRY_AMOUNT ELSE 0 END))*-1) AS SALES,
	SUM ((CASE WHEN MAIN_ACCOUNT_ID = '3411' THEN JOURNAL_ENTRY_AMOUNT ELSE 0 END)) AS COGS,
	FISCAL_SET_CURRENCY_CODE AS LOCAL_CURRENCY
	FROM ENT_FINANCE_TESTCLONE_CLONE_HENJOS.sara_mp_stg.stg_sara_mp_pjt0
	WHERE CURRENCY_TYPE = 'F'
	AND MAIN_ACCOUNT_ID IN ('3211','3411') 
	AND ORG_CODE = '9757L'
	AND FISCAL_YEAR = YEAR(GETDATE())
	AND COMP_PERIOD BETWEEN '0' AND REPMONTH 
	GROUP BY COMPANY_CODE,FISCAL_YEAR, JOURNAL_PERIOD, COMP_PERIOD, MAIN_ACCOUNT_ID, SOURCE, INTCO_MP, LOCAL_CURRENCY
),
INTERNAL_CUST AS
(
    SELECT
    CUSTOMER_NUMBER,
    COMPANY_NAME, 
    CITY, 
    COUNTRY, 
    LEGAL_UNIT, 
    CURRENCY, 
    TINA, 
    SOC, 
    ACTIVE, 
    ORDER_HANDLING_SYSTEM, 
    COMMENTS, 
    SAP_BUSPARTNER_ID
    FROM ENT_FINANCE_TESTCLONE_CLONE_HENJOS.data_entry_stg.stg_me_sap_internal_customer	
),
JOINED_UNADJUSTED AS
(
	SELECT
	COMPANY_CODE,
	FISCAL_YEAR,
	JOURNAL_PERIOD,
	REPYEAR,
	REPMONTH,
	MAIN_ACCOUNT_ID,
	SOURCE, 
	INTCO_MP, 
	LOCAL_CURRENCY,
	SALES,
	COGS,
	INTERNAL_CUST.LEGAL_UNIT AS INTCO,
	INTERNAL_CUST.COMPANY_NAME AS COMPANY_NAME
	FROM UNADJ_MARGIN
	LEFT JOIN INTERNAL_CUST
	ON UNADJ_MARGIN.INTCO_MP = INTERNAL_CUST.CUSTOMER_NUMBER 
),
MARG_ADJUST AS 
(
	SELECT
	left(ORG_CODE,4) AS COMPANY_CODE_M ,
	FISCAL_YEAR AS FISCAL_YEAR_M,
	JOURNAL_PERIOD AS JOURNAL_PERIOD_M, 
	--FISCAL_YEAR__PERIOD AS FISCAL_YEAR__PERIOD_M,
	CAST (MONTH(GETDATE()) -1 AS VARCHAR) AS REPMONTH_M,
	(CASE WHEN JOURNAL_PERIOD = '000' THEN '0' ELSE LTRIM(JOURNAL_PERIOD,'0') END) AS COMP_PERIOD_M, 
	'MP' as SOURCE_M,
	SUM ((CASE WHEN (MAIN_ACCOUNT_ID BETWEEN '1311' AND '1379' OR MAIN_ACCOUNT_ID BETWEEN '1390' AND '1399' ) THEN JOURNAL_ENTRY_AMOUNT ELSE 0 END)) as UNADJ_STOCK,
	SUM ((CASE WHEN (MAIN_ACCOUNT_ID BETWEEN '1380' AND '1389' ) THEN JOURNAL_ENTRY_AMOUNT ELSE 0 END)) as REVAL_STOCK,
	SUM (UNADJ_STOCK) OVER (PARTITION BY COMPANY_CODE_M, FISCAL_YEAR_M ORDER BY COMP_PERIOD_M ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMUL_STOCK,
	SUM (REVAL_STOCK) OVER (PARTITION BY COMPANY_CODE_M, FISCAL_YEAR_M ORDER BY COMP_PERIOD_M ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMUL_REVAL,
	--(CASE WHEN REVAL_STOCK > 0 THEN (UNADJ_STOCK  + REVAL_STOCK)/ UNADJ_STOCK ELSE 1 END) AS MARGIN_ADJUSTMENT,
	FISCAL_SET_CURRENCY_CODE AS LOCAL_CURRENCY_M
	FROM ENT_FINANCE_TESTCLONE_CLONE_HENJOS.sara_mp_stg.stg_sara_mp_pjt0
	WHERE CURRENCY_TYPE = 'F'
	AND ((MAIN_ACCOUNT_ID BETWEEN '1311' AND '1399'))
	AND ORG_CODE = '9757L'
	AND FISCAL_YEAR = YEAR(GETDATE())
	AND (CASE WHEN JOURNAL_PERIOD = '00' THEN '0' ELSE LTRIM(JOURNAL_PERIOD,'0') END) BETWEEN '0' AND REPMONTH_M 
	GROUP BY COMPANY_CODE_M, FISCAL_YEAR_M, JOURNAL_PERIOD_M, REPMONTH_M, COMP_PERIOD_M, SOURCE_M, LOCAL_CURRENCY_M
),
JOINED_ADJUST_MARG AS
(
	SELECT 
	COMPANY_CODE,
	FISCAL_YEAR,
	CONCAT (FISCAL_YEAR,'0',JOURNAL_PERIOD) AS FISCAL_YEAR__PERIOD,
	JOURNAL_PERIOD,
	REPYEAR,
	REPMONTH,
	MAIN_ACCOUNT_ID,
	--COMP_PERIOD,
	SOURCE, 
	INTCO,
	COMPANY_NAME, 
	LOCAL_CURRENCY,
	SUM (SALES) AS SALES,
	SUM (COGS) AS COGS,
	YEAR(GETDATE()) AS YEAR,
	MONTH(GETDATE()) AS MONTH, 
	DAY(GETDATE()) AS DAY,
	--MARG_ADJUST.REPMONTH_M,
	MARG_ADJUST.COMP_PERIOD_M AS PERIOD,
	SUM (MARG_ADJUST.UNADJ_STOCK) AS UNADJUSTED_STOCK,
	SUM (MARG_ADJUST.REVAL_STOCK) AS REVALUE,
	SUM (MARG_ADJUST.CUMUL_STOCK) AS CUMULATED_STOCK,
	SUM (MARG_ADJUST.CUMUL_REVAL) AS CUMULATED_REVALUED_STOCK,
	--MARG_ADJUST.MARGIN_ADJUSTMENT
	(CASE WHEN UNADJUSTED_STOCK < 0 THEN (UNADJUSTED_STOCK  + REVALUE)/ UNADJUSTED_STOCK ELSE 1 END) AS MARGIN_ADJUSTMENT,
	(SUM (COGS) * MARGIN_ADJUSTMENT) AS ADJ_COGS,
	(CASE WHEN SUM (SALES) = 0 THEN 1 ELSE (SUM (SALES)-ADJ_COGS) / (SUM (SALES)) END) AS ADJUSTED_MARGIN,
        (CASE WHEN CUMULATED_STOCK > 0 THEN (CUMULATED_STOCK  + CUMULATED_REVALUED_STOCK)/ CUMULATED_STOCK ELSE 1 END) AS MARGIN_ADJUSTMENT_PERIOD,
	(SUM (COGS) * MARGIN_ADJUSTMENT_PERIOD) AS ADJ_COGS_PERIOD,
	(CASE WHEN SUM (SALES) = 0 THEN 1 ELSE (SUM (SALES)-ADJ_COGS_PERIOD) / (SUM (SALES)) END) AS ADJUSTED_MARGIN_PERIOD
	FROM JOINED_UNADJUSTED
	LEFT JOIN MARG_ADJUST
	ON JOINED_UNADJUSTED.COMPANY_CODE = MARG_ADJUST.COMPANY_CODE_M AND
	JOINED_UNADJUSTED.FISCAL_YEAR = MARG_ADJUST.FISCAL_YEAR_M AND
	JOINED_UNADJUSTED.JOURNAL_PERIOD = MARG_ADJUST.JOURNAL_PERIOD_M
	GROUP BY 
	COMPANY_CODE,
	FISCAL_YEAR,
	JOURNAL_PERIOD,
	REPYEAR,
	REPMONTH,
	MAIN_ACCOUNT_ID,
	COMP_PERIOD_M,
	SOURCE, 
	INTCO,
	COMPANY_NAME, 
	LOCAL_CURRENCY,
	YEAR,
	MONTH,
	DAY
)
SELECT * FROM JOINED_ADJUST_MARG;